#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# branch name check

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex='^((bugfix|feature|release|hotfix|chore|refactor)\/.*)$'

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo "$message"
    exit 1
fi

# file count check

changedCount=$(git diff --name-only --cached | wc -l)
maxFilesPerCommit=20

if (( changedCount > maxFilesPerCommit )); then
  printf '%s\n' "Commit can only have a maximum of ${maxFilesPerCommit} file changes" >&2
  exit 1
fi